global:
  scrape_interval: 5s

rule_files:
  - "/etc/prometheus/rules/generated/*.yml"

scrape_configs:
  - job_name: "postgres"
    static_configs:
      - targets:
          - "postgres-exporter:9187"
