name: pytest-in-action-ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pytest-in-action:
    runs-on: ubuntu-latest
    env:
      PROMETHEUS_URL: ${{ secrets.PROMETHEUS_URL }}

    defaults:
      run:
        working-directory: ./pytest-in-action  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start test environment via Docker Compose
        run: docker compose up -d

      - name: Wait for services to be healthy
        run: |
            echo "Waiting for services to be ready..."
            sleep 30
            docker compose -f docker-compose.yml ps

             
      - name: Run PyTest
        run: |
          pytest src/tests \
            --junitxml=reports/test_results.xml \
            --html=reports/test_results.html \
            --self-contained-html -v

      - name: Tear down Docker Compose environment
        if: always()
        run: docker compose down -v
